### PR TITLE
UI Redesign

### PR DESCRIPTION
**Pull request by oxalorg**
Refers #13 and #11

### CODE REVIEW

**Comment by prodicus** [comment]
Great job! 

I observed this between.
screen shot 2017-06-17 at 1 30 38 pm

The huge gap between the rant text and the footer. What do you think?

**Comment by riturajDas** [comment]
- New color scheme is bomb.
- That gap is looking odd on mobile devices.
## To-do
- [ ] Fix mobile scaling

**Comment by oxalorg** [comment]
> New color scheme is bomb

Thanks @riturajDas 😸 

Yeah there was an issue with the viewport, just pushed the fix.



(*Share/refresh buttons not visible above because they got blocked by Privacy Badger*)

**Comment by riturajDas** [comment]
It scales now? awesome!  @prodicus put this iteration up, looks crisp👌🏽 imo.

**Pull request merged**
